name: flights_logger
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  pointer_interceptor: ^0.10.1+1
  provider: ^6.1.2
  uuid: ^4.4.0
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  path: ^1.9.0
  sqflite_common_ffi:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # sqflite_common_ffi: ^2.3.3


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
